### ISSUE TITLE
Not enough Accuracy in picking the particles

### ISSUE THREAD

**Issue by SanatMoharir** [PrincetonUniversity/APPLEpicker-python#22]
I asked @ayeltg and @janden How to increase the accuracy in picking the particles and authors told me to use the config file to customize the tau2 parameter. I have tried it but it is not picking all the parameters correctly can you please help me with the right approach. I have motion corrected .mrc images of particles and after calibration I am getting this output:
![sample_result](https://user-images.githubusercontent.com/40124637/53545772-984b3980-3b50-11e9-910e-a3eaf464c261.jpg)

**Comment by ayeltg** [comment]
Is this a dataset from empiar?

**Comment by SanatMoharir** [comment]
No, actually it is from research institute in Pune, India.

**Comment by ayeltg** [comment]
Visually, it seems that many of the projections are very close together. The apple picker probably identifies them as a single projection region and then either discards them as the region is too large, or misidentifies the center of this region as a particle center. In a few months we should be ready to publish code that fixes this issue. For now, working on a ctf corrected micrograph may help a little (although we have never tried to pick particles from ctf corrected micrographs that were collected using phase plates).

Also, if you can upload a sample micrograph, I would be happy to try to pick particles and see if I can improve the accuracy somewhat.

**Comment by SanatMoharir** [comment]
Yes, for sure XD 
I have created a google drive link:
https://drive.google.com/drive/folders/12FDYd676x6UWF78RCoGcfWyIAeeiJBjB?usp=sharing

Please see if you can increase the picking accuracy, thanks in advance !!!

**Comment by ayeltg** [comment]
I've ran the apple-picker on your micrograph. The problem indeed is that nearby particles are classified as a single particle region. I'm attaching the segmentation to particle and noise regions from the apple picker:
![classification](https://user-images.githubusercontent.com/32773943/53667234-6a442300-3c3e-11e9-8d4c-076ba2c9d497.jpg)

One way to deal with this is to set tau1 and tau2 so that very few windows are used for particle training and very many windows are used for noise training. The issue with this is that it will produce several non-centered identification of a single particle:
![multiple](https://user-images.githubusercontent.com/32773943/53667238-70d29a80-3c3e-11e9-8883-c3ba0732bbf1.jpg)

As I mentioned, in a few months we should have code that can deal with this, and produce results that are better than:
![future](https://user-images.githubusercontent.com/32773943/53667280-8ba50f00-3c3e-11e9-98cb-7269c8cfdbae.jpg)
