### ISSUE TITLE
Guidance on Taus

### ISSUE THREAD

**Issue by mirgow** [PrincetonUniversity/APPLEpicker-python#25]
Hello, I’m trying to understand better how the tau1 and tau2 parameters in the APPLE particle picker work - I can see from the paper they’re defined as “the percentage of training images that we believe do contain a particle” and “the percentage of training images that we believe may contain a particle,” respectively, but I’m not fully understanding that description. Also, in the config.ini files, these parameters are set as integers above 100 (as in, not percent values) - what are your guidelines for setting these tau parameters for a dataset? I would appreciate any help.

**Comment by ayeltg** [comment]
Hi, thanks for your interest in the apple picker!

First, I will give a little background: 
The apple picker extracts query windows from the micrograph and assigns a score to each. The higher a window scores, the more likely it contains a particle projection. In the next step, we would like to train an SVM classifier from a subset of these windows. That is, we would like to use some query windows as positive examples (projections) and others as negative examples (noise). For this training we will only use the query windows most likely to contain a projection and those most likely to contain noise. In the python version, we use as positive example the tau1 highest scoring query windows; As these windows scored the highest, they are the most likely to contain projections. Next, we locate the negative examples. We do not use all the remaining query windows as negative examples since the query windows have some overlap. Rather, we use any query window that has no overlap with the tau2 highest scoring query windows.

You are correct that in this code tau1 and tau2 are integers -- they are the number of query windows rather than the percentage. The overall number of query windows is approximately (2N/M) squared (where the micrograph is of size NxN and the query windows are MxM), so the conversion to percentage is straightforward. 

As for some rules of thumb:
tau1 can usually be set to 600. In micrographs with very many projections you should increase this number, and in micrographs with very few projections you should decrease it. 
tau2 has a larger dependence on the size of your micrograph and query window.  You should usually use 30%-50% of the number of query windows (2N/M squared) as tau2. Again, in micrographs with very many or very few projections this should be adjusted.

Let me know if you have any more questions,
Ayelet
